// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.707
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func BaseLayout() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><link rel=\"stylesheet\" href=\"/static/css/base.css\"><link rel=\"stylesheet\" href=\"/static/css/contact.css\"><link rel=\"stylesheet\" href=\"/static/css/project.css\"><link rel=\"stylesheet\" href=\"/static/css/cv.css\"><title>Personal Portfolio</title><script src=\"https://unpkg.com/htmx.org@2.0.0/dist/htmx.js\" integrity=\"sha384-Xh+GLLi0SMFPwtHQjT72aPG19QvKB8grnyRbYBNIdHWc2NkCrz65jlU7YrzO6qRp\" crossorigin=\"anonymous\"></script></head><body><header><nav class=\"primary-nav\"><ul><li><a hx-replace-url=\"true\" hx-patch=\"/about\" hx-trigger=\"click\" hx-target=\"#contents\">About Me</a></li><li><a hx-replace-url=\"true\" hx-patch=\"/projects\" hx-trigger=\"click\" hx-target=\"#contents\">Projects</a></li><li><a hx-patch=\"/cv\" hx-replace-url=\"true\" hx-trigger=\"click\" hx-target=\"#contents\">CV</a></li><li><a hx-patch=\"/contact\" hx-replace-url=\"true\" hx-trigger=\"click\" hx-target=\"#contents\">Contact</a></li></ul></nav></header><div class=\"primary-content\" id=\"contents\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div><footer><ul><li><a href=\"https://www.linkedin.com/in/simon-vinding-brodersen/\"><img width=\"24\" height=\"24\" src=\"/static/img/LinkedIn-Logos/LI-In-Bug.png\" alt=\"LinkedIn SVG\"></a></li><li><a href=\"https://github.com/svbrodersen\"><picture><source srcset=\"/static/img/github-mark/github-mark-white.png\" media=\"(prefers-color-scheme: dark)\"> <img width=\"24\" height=\"24\" src=\"/static/img/github-mark/github-mark.png\" alt=\"Github SVG\"></picture></a></li></ul></footer></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
